### ISSUE TITLE
github links run together

### ISSUE THREAD

**Issue by IllIllI000** [code4rena-dev/botrace-utils#7]
https://github.com/code-423n4/2024-02-ai-arena/blob/main/bot-report.md#l-11-the-owner-is-a-single-point-of-failure-and-a-centralization-risk all of the links appear as a concatenation of the urls into a single link

**Comment by jacobheun** [comment]
Thanks for submitting, looks like a spacing problem when urls aren't wrapped. Will open a PR to resolve this.
